### ISSUE TITLE
Remove xarray-dataclasses dependency.

### ISSUE THREAD

**Issue by jejjohnson** [jejjohnson/ocn-tools#5]
This has some dependency issues that make things unnecessarily difficult.  We have a monkey patch for now, but I think it's worth removing.

To remove this, we would need to refactor the [`test_geostrophic.py`](https://github.com/jejjohnson/oceanbench/blob/master/oceanbench/_src/geoprocessing/test_geostrophic.py) file. 

We can use the the example for the [`test_gridding.py`](https://github.com/jejjohnson/ocn-tools/blob/main/ocn_tools/_src/geoprocessing/test_gridding.py) file.

**Tasks**

* [x] Refactor Tests without `xarray.dataclasses`
* [x] Remove dependency in `.yaml` files
* [ ] Remove dependency in .github actions
